class_name ArmoryVisualsData
extends RefCounted
## Armory v2 visual data (items-and-armory.md §3.8; weapons-and-mods.md
## §3.6.2-§3.6.3 tier channels, §3.7.1 tracer / impact per ammo type), read
## from assets/data/visuals/armory_visuals.json (generated by
## tools/art/gen_armory_visuals.py). Presentation only: never read by the sim.

const PATH := "res://assets/data/visuals/armory_visuals.json"

static var _data: Dictionary = {}
static var _catalog: ArmoryCatalogDef = null


## The parsed data (loaded once; empty Dictionary if the file is missing).
static func data() -> Dictionary:
	if _data.is_empty():
		var f := FileAccess.open(PATH, FileAccess.READ)
		if f != null:
			var v: Variant = JSON.parse_string(f.get_as_text())
			if v is Dictionary:
				_data = v
	return _data


## The v22 catalog the build indices refer to (§3.11 wire order). Tests and
## tools may inject another one with set_catalog().
static func catalog() -> ArmoryCatalogDef:
	if _catalog == null:
		_catalog = load(ArmoryCatalogDef.DEFAULT_PATH) as ArmoryCatalogDef
	return _catalog


static func set_catalog(c: ArmoryCatalogDef) -> void:
	_catalog = c


## Idle VFX cull distance (m), §3.8 rule 6 / weapons-and-mods.md R9.
static func idle_cull_m() -> float:
	return float(data().get("idle_cull_m", 30.0))


## Tier channel scale for visual tier 1..3 (Component / Assembly / Signature).
static func tier_size(tier: int) -> float:
	var a: Array = data().get("tier_size", [1.0, 1.4, 1.9])
	return float(a[clampi(tier, 1, a.size()) - 1])


static func tier_glow(tier: int) -> float:
	var a: Array = data().get("tier_glow", [0.6, 1.0, 1.6])
	return float(a[clampi(tier, 1, a.size()) - 1])


## Base scale of body gear meshes (silhouette first, §3.8 rule 6).
static func gear_base_scale() -> float:
	return float(data().get("gear_base_scale", 1.0))


## Glow factor of a spare (§3.4 rule 3: shown unlit).
static func spare_dim() -> float:
	return float(data().get("spare_dim", 0.15))


## Crystal / chip cut of a weapon item line (colour-blind backup, art bible §7.2).
static func item_cut(id: StringName) -> String:
	return String((data().get("item_cuts", {}) as Dictionary).get(String(id), ""))


## Body gear shape key of an open-slot gear item ("" = generic).
static func gear_shape(id: StringName) -> String:
	return String((data().get("gear_shapes", {}) as Dictionary).get(String(id), ""))


## Tracer / impact tell of a DamageMath ammo type (Standard if unknown).
## Keys: name, color ("" = team colour), width, length, shape, impact.
static func ammo_tell(ammo_type: int) -> Dictionary:
	var a: Dictionary = data().get("ammo", {})
	return a.get(str(ammo_type), a.get("0", {"name": "standard", "color": "", "width": 1.0,
		"length": 1.0, "shape": "plain", "impact": "spark"}))


## Ammo Mod modifiers of a DamageMath mod id ({} = none).
static func mod_tell(mod: int) -> Dictionary:
	return (data().get("ammo_mods", {}) as Dictionary).get(str(mod), {})


## Tracer colour of an ammo type, or `fallback` for Standard.
static func ammo_color(ammo_type: int, fallback: Color) -> Color:
	var c := String(ammo_tell(ammo_type).get("color", ""))
	return Color(c) if c != "" else fallback


## Anchor table (anchor name -> {subs, overflow, fp}).
static func anchors() -> Dictionary:
	return data().get("anchors", {})


## Per-hero preset (spread, gear_scale, nudge) with the default as fallback.
static func hero_preset(hero_key: StringName) -> Dictionary:
	var h: Dictionary = data().get("heroes", {})
	return h.get(String(hero_key), h.get("default", {"spread": 1.0, "gear_scale": 1.0, "nudge": {}}))


static func badge() -> Dictionary:
	return data().get("badge", {"bone": "UpperChest", "pos": [0.0, 0.0, 0.2], "step": [0.045, 0.0, 0.0]})


static func bone_fallback(bone: String) -> Vector3:
	var a: Array = (data().get("bone_fallback", {}) as Dictionary).get(bone, [0.0, 1.2, 0.0])
	return vec(a)


static func vec(a: Variant) -> Vector3:
	if a is Array and (a as Array).size() >= 3:
		return Vector3(float(a[0]), float(a[1]), float(a[2]))
	return Vector3.ZERO
