class_name AudioEventDef
extends Resource
## W21-A1: one sound event (design/audio/audio-events.md). Presentation data
## only; generated by tools/audio/write_event_defs.py from tools/audio/catalog.py
## and tuned here. Streams resolve in this order (AudioEventBank):
##   1. `streams` (explicit resources), 2. `file_paths`,
##   3. convention res://assets/audio/<folder>/<file_stem>_NN.ogg (NN = 01..),
##   4. `synth_recipe` (an SfxSynth archetype, the in-code fallback).
## Dropping recorded CC0 files with the convention names replaces the rendered
## ones with no code change.

enum Spatial { FLAT_2D, POSITIONAL_3D }
## Who may trigger the event relative to the local player.
enum OwnerFilter { ANY, OWN, ENEMY, ALLY }

@export var id: StringName
## Folder under res://assets/audio/ (e.g. "weapons", "abilities/hex").
@export var folder: String = ""
## File stem; variants are <file_stem>_01.ogg, _02.ogg, ...
@export var file_stem: String = ""
@export var streams: Array[AudioStream] = []
@export var file_paths: PackedStringArray = PackedStringArray()
## SfxSynth archetype used when no file resolves ("" = silent).
@export var synth_recipe: StringName = &""
## Bus name (GameSettings.BUS_*).
@export var bus: StringName = &"Effects"
@export var spatial: Spatial = Spatial.FLAT_2D
## 3D only: beyond this the event is not started (0 = engine default, unlimited).
@export var max_distance_m: float = 0.0
## 3D only: distance (m) at which the attenuation is 0 dB.
@export var unit_size: float = 10.0
## 3D only: AudioStreamPlayer3D.AttenuationModel.
@export var attenuation: int = 0
@export var volume_db: float = 0.0
## Random +- volume (dB) and pitch-scale spread per play.
@export var vol_jitter_db: float = 1.0
@export var pitch: float = 1.0
@export var pitch_jitter: float = 0.03
## 0 = most important (never stolen by lower), 3 = least.
@export_range(0, 3) var priority: int = 2
## Priority beyond `priority_range_m` (-1 = same as `priority`).
@export_range(-1, 3) var far_priority: int = -1
@export var priority_range_m: float = 0.0
## Simultaneous voices of this event; the oldest is stolen past the limit.
@export_range(1, 16) var max_voices: int = 4
## Minimum time between two starts of this event (0 = none).
@export var cooldown_ms: int = 0
@export var owner_filter: OwnerFilter = OwnerFilter.ANY
## Extra gain while GameSettings.night_mode is on (explosions / ults: -4 dB).
@export var night_db: float = 0.0
@export var loop: bool = false


## Effective priority at `distance_m` from the listener (2D events: always `priority`).
func priority_at(distance_m: float) -> int:
	if far_priority < 0 or priority_range_m <= 0.0 or distance_m <= priority_range_m:
		return priority
	return far_priority


## True when an event triggered by `relation` (OwnerFilter OWN / ENEMY / ALLY) may play.
func accepts(relation: int) -> bool:
	return owner_filter == OwnerFilter.ANY or owner_filter == relation


## Convention path of variant `n` (1-based).
func convention_path(n: int) -> String:
	return "res://assets/audio/%s/%s_%02d.ogg" % [folder, file_stem, n]
