class_name ArmoryCatalogDef
extends Resource
## The Armory catalog (v2 recipe catalog, items-and-armory.md §3.11, protocol 22),
## generated by tools/armory/build_catalog.py. Server, client, bots and tools
## all load this path. Item order is the wire index (InputCommand ACTION_BUY /
## ProgressState): append items only.
const DEFAULT_PATH := "res://assets/data/economy/armory_catalog_v22.tres"


## Path of the catalog in use (always DEFAULT_PATH; the v1 catalog is gone).
static func active_path() -> String:
	return DEFAULT_PATH

@export var items: Array[ArmoryItemDef] = []


func index_of(id: StringName) -> int:
	for i in items.size():
		if items[i] != null and items[i].id == id:
			return i
	return -1


func find(id: StringName) -> ArmoryItemDef:
	var i := index_of(id)
	return items[i] if i >= 0 else null


func at(index: int) -> ArmoryItemDef:
	return items[index] if index >= 0 and index < items.size() else null


## True for the Armory v2 recipe catalog (any item with a recipe tier).
func is_recipe_catalog() -> bool:
	for it in items:
		if it != null and it.tier != ArmoryItemDef.Tier.NONE:
			return true
	return false
